name: code review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: install deps
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore
      - name: test
        run: dotnet test --no-build --verbosity normal